databases:
  - name: today_coordinate
    region: oregon
    plan: free
    user: today_coordinate

services:
  - type: web
    name: today_coordinate
    env: python
    region: oregon
    buildCommand: './build.sh'
    startCommand: 'gunicorn config.wsgi'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: today_coordinate
          property: connectionString
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: '3.9.25'
    autoDeploy: true
