# Generated by Django 4.2.15 on 2026-06-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('category', models.CharField(choices=[('tops', 'トップス'), ('bottoms', 'ボトムス'), ('onepiece', 'ワンピース・セットアップ'), ('onepiece-tops', 'ワンピース用カーディガン'), ('shoes', 'シューズ'), ('hair', 'ヘアアレンジ')], max_length=100, verbose_name='カテゴリー')),
                ('season', models.CharField(choices=[('spring', '春'), ('summer', '夏'), ('autumn', '秋'), ('winter', '冬'), ('all', 'オール')], max_length=100, verbose_name='季節')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新規更新日時')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
