"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool('DEBUG')

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    "coordinate",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'django_bootstrap5',
    
    'django.contrib.sites',
    
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
    # 'default': dj_database_url.parse('mysql://root:@localhost:3306/django_coordinate'),
    'default': env.db()
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 共通スタティックファイルディレクトリ設定
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# 本番環境でスタティックファイルを集積するディレクトリ設定
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# フォーム処理を実行可能なドメイン設定
CSRF_TRUSTED_ORIGINS = ['https://*.amazonaws.com']

# フラッシュメッセージ設定
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'alert alert-secondary',
    messages.INFO: 'alert alert-info',
    messages.SUCCESS: 'alert alert-success',
    messages.WARNING: 'alert alert-warning',
    messages.ERROR: 'alert alert-danger',
}

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

# Django-bootstrap5関連の設定
BOOTSTRAP5 = {
    'javascript_in_head': False,
    'inline_wrapper_class': 'mb-3',
}
# Django-bootstrap5関連の設定ここまで

# # Django-allauth関連の設定
# AUTHENTICATION_BACKENDS = [
#     "django.contrib.auth.backends.ModelBackend",
#     "allauth.account.auth_backends.AuthenticationBackend",
    
# ]

# # 認証に利用するサイト番号
# SITE_ID = 1
# # 認証に利用するフィールド
# ACCOUNT_AUTHENTICATION_METHOD = 'email'
# # ユーザ名は必須ではない
# ACCOUNT_USERNAME_REQUIRED = False
# # メールは必須
# ACCOUNT_EMAIL_REQUIRED = True
# # メールの認証は行わない
# ACCOUNT_EMAIL_VERIFICATION = 'none'
# # ログアウトはGETで実行
# ACCOUNT_LOGOUT_ON_GET = True
# # ログイン用アクション
# LOGIN_URL = 'account_login'
# # ログイン後に遷移するアクション
# LOGIN_REDIRECT_URL = 'coordinate:dashboard'
# # ログアウト後に遷移するアクション
# ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'
# # 利用するユーザモデル
# AUTH_USER_MODEL = 'user.CustomUser'
# # HTTPSプロトコルで動作
# ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
# SOCIALACCOUNT_PROVIDERS = {
#     'google': {
#         'APP': {
#         },
#         'SCOPE': [
#             'profile',
#             'email',
#         ],
#         'AUTH_PARAMS': {
#             'access_type': 'online',
#         },
#     }
# }
# # Django-allauth関連の設定ここまで

MEDIA_ROOT=os.path.join(BASE_DIR,'media')
MEDIA_URL='/media/'

# RENDERでの設定

RENDER = env.bool('RENDER')
if RENDER:
    MIDDLEWARE += [
        "django.middleware.security.SecurityMiddleware",
        "whitenoise.middleware.WhiteNoiseMiddleware",    
    ]
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    